# Generated by Django 5.2.8 on 2025-11-30 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_transcriptions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(default='hi', max_length=10)),
                ('model_name', models.CharField(default='tiny', max_length=50)),
                ('total_words', models.PositiveIntegerField(blank=True, null=True)),
                ('high_confidence_words', models.PositiveIntegerField(blank=True, null=True)),
                ('average_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='project_manager.project')),
            ],
        ),
        migrations.CreateModel(
            name='WordTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('transliterated_word', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time_seconds', models.FloatField()),
                ('end_time_seconds', models.FloatField()),
                ('start_sample', models.PositiveIntegerField(blank=True, null=True)),
                ('end_sample', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('is_high_confidence', models.BooleanField(default=False)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_timestamps', to='audio_transcription.audiotranscription')),
            ],
            options={
                'ordering': ['start_time_seconds'],
            },
        ),
    ]
