# Generated by Django 5.2.8 on 2025-11-30 10:34

import audio_transcription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotranscription',
            name='audio_file',
            field=models.FileField(upload_to=audio_transcription.models.project_audio_upload_path),
        ),
    ]
