# Generated by Django 5.2.8 on 2025-11-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_transcription', '0002_alter_audiotranscription_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiotranscription',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
