# Generated by Django 5.2.8 on 2026-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_transcription', '0003_alter_audiotranscription_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotranscription',
            name='progress_message',
            field=models.CharField(blank=True, help_text='Current processing step', max_length=255),
        ),
        migrations.AddField(
            model_name='audiotranscription',
            name='progress_percentage',
            field=models.FloatField(default=0.0, help_text='Progress percentage (0-100)'),
        ),
    ]
