# Generated by Django 5.2.8 on 2026-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_transcription', '0004_audiotranscription_progress_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotranscription',
            name='video_progress_message',
            field=models.CharField(blank=True, help_text='Current video processing step', max_length=255),
        ),
        migrations.AddField(
            model_name='audiotranscription',
            name='video_progress_percentage',
            field=models.FloatField(default=0.0, help_text='Video progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='audiotranscription',
            name='video_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
