# Generated by Django 5.2.8 on 2025-11-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio_transcription', '0003_alter_audiotranscription_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('content', 'Content'), ('neutral', 'Neutral'), ('love', 'Love'), ('excitement', 'Excitement')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('word_timestamp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_annotation', to='audio_transcription.wordtimestamp')),
            ],
            options={
                'ordering': ['word_timestamp__start_time_seconds'],
            },
        ),
    ]
