# Generated by Django 5.2.8 on 2025-11-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
        ('audio_transcription', '0003_alter_audiotranscription_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionannotation',
            name='emotion',
            field=models.CharField(choices=[('angry', 'Angry'), ('bore', 'Bore'), ('content', 'Content'), ('glare', 'Glare'), ('happy', 'Happy'), ('sad', 'Sad'), ('sarcasm', 'Sarcasm'), ('worried', 'Worried')], max_length=20),
        ),
        migrations.CreateModel(
            name='BodyPostureAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posture', models.CharField(choices=[('brave', 'Brave'), ('cross_hands', 'Cross Hands'), ('hello', 'Hello'), ('listen', 'Listen'), ('me', 'Me'), ('no', 'No'), ('point', 'Point'), ('that', 'That'), ('think', 'Think'), ('this', 'This'), ('why', 'Why'), ('wow', 'Wow')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('word_timestamp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_posture_annotation', to='audio_transcription.wordtimestamp')),
            ],
            options={
                'ordering': ['word_timestamp__start_time_seconds'],
            },
        ),
    ]
