# Generated by Django 5.2.8 on 2025-12-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_modeannotation'),
        ('audio_transcription', '0003_alter_audiotranscription_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(choices=[('character1', 'Character 1'), ('character2', 'Character 2')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_timestamp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character_annotation', to='audio_transcription.wordtimestamp')),
            ],
            options={
                'ordering': ['word_timestamp__start_time_seconds'],
            },
        ),
    ]
