# Generated by Django 5.2.8 on 2025-12-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_characterannotation'),
        ('audio_transcription', '0003_alter_audiotranscription_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_type', models.CharField(choices=[('green', 'Green Background'), ('white', 'White Background'), ('custom_color', 'Custom Color'), ('custom_image', 'Custom Image')], max_length=20)),
                ('background_value', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('word_timestamp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_annotation', to='audio_transcription.wordtimestamp')),
            ],
            options={
                'ordering': ['word_timestamp__start_time_seconds'],
            },
        ),
    ]
