# Generated by Django 5.2.8 on 2025-12-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20251201_1749'),
        ('audio_transcription', '0003_alter_audiotranscription_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.PositiveIntegerField()),
                ('time_seconds', models.FloatField()),
                ('word', models.CharField(blank=True, max_length=100)),
                ('phoneme', models.CharField(blank=True, max_length=20)),
                ('emotion', models.CharField(blank=True, max_length=20)),
                ('body_posture', models.CharField(blank=True, max_length=20)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('character', models.CharField(blank=True, max_length=20)),
                ('background', models.CharField(blank=True, max_length=20)),
                ('head_direction', models.CharField(choices=[('L', 'Left'), ('M', 'Middle'), ('R', 'Right')], default='M', max_length=5)),
                ('eye_direction', models.CharField(choices=[('L', 'Left'), ('M', 'Middle'), ('R', 'Right')], default='M', max_length=5)),
                ('head_tilt', models.IntegerField(default=0)),
                ('zoom_level', models.FloatField(default=1.0)),
                ('blink', models.BooleanField(default=False)),
                ('media', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_annotations', to='audio_transcription.audiotranscription')),
            ],
            options={
                'ordering': ['frame_number'],
                'unique_together': {('transcription', 'frame_number')},
            },
        ),
    ]
