# Generated by Django 5.2.8 on 2025-12-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_frameannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameannotation',
            name='intensity',
            field=models.BooleanField(default=False),
        ),
    ]
